# Generated by Django 5.0.6 on 2024-06-22 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_addingCategories'),
        ('blog', '0002_post_image'),
    ]

    operations = [
    ]
