# Generated by Django 5.0.6 on 2024-07-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_post_etiqueta_post_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="excerpt",
            field=models.TextField(default="", verbose_name="Bajada"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=200, unique=True, verbose_name="Nombre"),
        ),
    ]
